[pt_table]
#partition table is 4K in size
address0 = 0xE000
address1 = 0xF000
version = 2

[[pt_entry]]
type = 16
name = "Boot2"
device = 0
address0 = 0
size0 = 0xE000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
header = 1
security = 1

[[pt_entry]]
type = 0
name = "FW"
device = 0
address0 = 0x10000
size0 = 0x76C000
address1 = 0x77C000
size1 = 0x76C000
# compressed image must set len,normal image can left it to 0
len = 0
header = 1
security = 1

[[pt_entry]]
type = 3
name = "mfg"
device = 0
address0 = 0x77C000
size0 = 0x76C000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
header = 1
security = 1

[[pt_entry]]
type = 5
name = "media"
device = 0
address0 = 0xEE8000
size0 = 0xB8000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
header = 0
security = 0

[[pt_entry]]
type = 6
name = "kv"
device = 0
address0 = 0xFA0000
size0 = 0x2000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
header = 0
security = 0

[[pt_entry]]
type = 7
name = "factory"
device = 0
address0 = 0xFA2000
size0 = 0x1000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
header = 0
security = 0

[[pt_entry]]
type = 8
name = "user"
device = 0
address0 = 0xFA3000
size0 = 0x5D000
address1 = 0
size1 = 0
# compressed image must set len,normal image can left it to 0
len = 0
header = 0
security = 0

